language: python

python:
  - "3.6"

before_install:
  - openssl aes-256-cbc -K $encrypted_f46fd4646bd0_key -iv $encrypted_f46fd4646bd0_iv -in deployments.tar.enc -out deployments.tar -d
  - tar xvf deployments.tar
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
    CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version
  - gcloud components install kubectl || true
  - pip install pipenv

install:
  - pipenv install --system --deploy

script:
  - ./src/manage.py test --settings=conf.settings.test

deploy:
- provider: script
  skip_cleanup: true
  script: bash ./deploy.sh production
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: bash ./deploy.sh staging
  on:
    branch: staging
