# Generated by Django 2.1.3 on 2018-11-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcontent',
            name='purpose',
            field=models.CharField(choices=[('email_verification', 'Email verification')], max_length=100),
        ),
    ]
