# Generated by Django 2.1.3 on 2018-11-16 08:40

import common.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('phone_verification', 'Phone verification')], max_length=100)),
                ('language', common.model_fields.LanguageField(choices=[('km', 'Cambodian'), ('en', 'English'), ('id', 'Indonesian')], max_length=10)),
                ('content', models.CharField(max_length=200)),
                ('target', models.CharField(choices=[('user', 'User'), ('system', 'System')], max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='smscontent',
            unique_together={('purpose', 'language')},
        ),
    ]
