# Generated by Django 2.1.3 on 2018-11-27 03:45

import common.model_fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20181119_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.CharField(choices=[('about_us', 'About Us'), ('privacy_agreement', 'Privacy and Agreement')], max_length=100)),
                ('language', common.model_fields.LanguageField(choices=[('km', 'Cambodian'), ('en', 'English'), ('id', 'Indonesian')], max_length=10)),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='staticpage',
            unique_together={('page', 'language')},
        ),
    ]
