# Generated by Django 2.1.3 on 2018-11-27 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20181127_0430'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
    ]
