# Generated by Django 2.1.3 on 2018-12-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_auto_20181128_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='page',
            field=models.CharField(choices=[('about_us', 'About Us'), ('privacy', 'Privacy'), ('agreement', 'Agreement'), ('promotion_programs', 'Promotion Programs')], max_length=100),
        ),
    ]
