# Generated by Django 2.1.3 on 2018-12-11 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_auto_20181204_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailcontent',
            options={'verbose_name': 'Email Content', 'verbose_name_plural': 'Email Contents'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='smscontent',
            options={'verbose_name': 'SMS Content', 'verbose_name_plural': 'SMS Contents'},
        ),
        migrations.AlterModelOptions(
            name='staticpage',
            options={'verbose_name': 'Static Page', 'verbose_name_plural': 'Static Pages'},
        ),
    ]
