# Generated by Django 2.1.3 on 2018-12-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_auto_20181212_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
