# Generated by Django 2.1.4 on 2018-12-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_staticpage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='page',
            field=models.CharField(choices=[('about_us', 'About Us'), ('privacy', 'Privacy'), ('agreement', 'Agreement'), ('promotion_programs', 'Promotion Programs'), ('how_it_works', 'How It Works'), ('api_reference', 'API Reference'), ('digital_assets', 'Digital Assets')], max_length=100),
        ),
    ]
