# Generated by Django 2.1.4 on 2018-12-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_auto_20181220_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='page',
            field=models.CharField(choices=[('about-us', 'About Us'), ('privacy', 'Privacy'), ('agreement', 'Agreement'), ('promotion-programs', 'Promotion Programs'), ('how-it-works', 'How It Works'), ('api-reference', 'API Reference'), ('digital-assets', 'Digital Assets')], max_length=100),
        ),
    ]
