# Generated by Django 2.1.3 on 2018-11-15 06:43

import common.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', common.model_fields.CountryField(choices=[('KH', 'Cambodia'), ('ID', 'Indonesia'), ('PH', 'Philippines')], max_length=3)),
                ('currency', common.model_fields.FiatCurrencyField(choices=[('IDR', 'IDR'), ('PHP', 'PHP'), ('USD', 'USD')], max_length=5)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('bank_id', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('value_type', models.CharField(choices=[('int', 'Number'), ('decimal', 'Currency'), ('string', 'Text')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CountryCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', common.model_fields.CountryField(choices=[('KH', 'Cambodia'), ('ID', 'Indonesia'), ('PH', 'Philippines')], max_length=3)),
                ('currency', common.model_fields.FiatCurrencyField(choices=[('IDR', 'IDR'), ('PHP', 'PHP'), ('USD', 'USD')], max_length=5)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountryDefaultConfig',
            fields=[
                ('country', common.model_fields.CountryField(choices=[('KH', 'Cambodia'), ('ID', 'Indonesia'), ('PH', 'Philippines')], max_length=3, primary_key=True, serialize=False)),
                ('language', common.model_fields.LanguageField(choices=[('km', 'Cambodian'), ('en', 'English'), ('id', 'Indonesian')], max_length=10)),
                ('currency', common.model_fields.FiatCurrencyField(choices=[('IDR', 'IDR'), ('PHP', 'PHP'), ('USD', 'USD')], max_length=5)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('fee_type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], default='percentage', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PopularPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', common.model_fields.CountryField(choices=[('KH', 'Cambodia'), ('ID', 'Indonesia'), ('PH', 'Philippines')], max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='countrycurrency',
            unique_together={('country', 'currency')},
        ),
        migrations.AlterUniqueTogether(
            name='bank',
            unique_together={('country', 'currency')},
        ),
    ]
