# Generated by Django 2.1.3 on 2018-11-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('value_type', models.CharField(choices=[('int', 'Number'), ('decimal', 'Currency'), ('string', 'Text')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('fee_type', models.CharField(choices=[('int', 'Number'), ('decimal', 'Currency'), ('string', 'Text')], max_length=20)),
            ],
        ),
    ]
