# Generated by Django 2.1.3 on 2018-11-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularplace',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='popularplace',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='countrycurrency',
            unique_together={('country', 'currency')},
        ),
    ]
