# Generated by Django 2.1.3 on 2018-11-13 11:06

import common.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='country',
            field=common.model_fields.CountryField(choices=[('KH', 'Cambodia'), ('ID', 'Indonesia'), ('PH', 'Philippines')], max_length=3),
        ),
        migrations.AlterField(
            model_name='bank',
            name='currency',
            field=common.model_fields.FiatCurrencyField(choices=[('IDR', 'IDR'), ('PHP', 'PHP'), ('USD', 'USD')], max_length=5),
        ),
        migrations.AlterField(
            model_name='countrycurrency',
            name='country',
            field=common.model_fields.CountryField(choices=[('KH', 'Cambodia'), ('ID', 'Indonesia'), ('PH', 'Philippines')], max_length=3),
        ),
        migrations.AlterField(
            model_name='countrycurrency',
            name='currency',
            field=common.model_fields.FiatCurrencyField(choices=[('IDR', 'IDR'), ('PHP', 'PHP'), ('USD', 'USD')], max_length=5),
        ),
        migrations.AlterField(
            model_name='countrydefaultconfig',
            name='country',
            field=common.model_fields.CountryField(choices=[('KH', 'Cambodia'), ('ID', 'Indonesia'), ('PH', 'Philippines')], max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='countrydefaultconfig',
            name='currency',
            field=common.model_fields.FiatCurrencyField(choices=[('IDR', 'IDR'), ('PHP', 'PHP'), ('USD', 'USD')], max_length=5),
        ),
        migrations.AlterField(
            model_name='countrydefaultconfig',
            name='language',
            field=common.model_fields.LanguageField(choices=[('km', 'Cambodian'), ('en-PH', 'English'), ('id', 'Indonesian')], max_length=10),
        ),
        migrations.AlterField(
            model_name='popularplace',
            name='country',
            field=common.model_fields.CountryField(choices=[('KH', 'Cambodia'), ('ID', 'Indonesia'), ('PH', 'Philippines')], max_length=3),
        ),
    ]
