# Generated by Django 2.1.3 on 2018-11-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrydefaultconfig',
            name='country_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
