# Generated by Django 2.1.3 on 2018-11-14 03:46

import common.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_system', '0002_auto_20181113_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('email_verification', 'email_verification')], max_length=100)),
                ('language', common.model_fields.LanguageField(choices=[('km', 'Cambodian'), ('en-PH', 'English'), ('id', 'Indonesian')], max_length=10)),
                ('subject', models.CharField(max_length=500)),
                ('content', models.TextField(max_length=500)),
                ('target', models.CharField(choices=[('user', 'User'), ('system', 'System')], max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='emailcontent',
            unique_together={('purpose', 'language')},
        ),
    ]
