# Generated by Django 2.1.3 on 2018-11-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_system', '0002_countrydefaultconfig_country_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrydefaultconfig',
            name='phone_country_code',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
