# Generated by Django 2.1.3 on 2018-11-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_system', '0002_auto_20181108_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryDefaultConfig',
            fields=[
                ('country', models.CharField(choices=[('HK', 'Hong Kong'), ('VN', 'Viet Nam')], max_length=3, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('en-US', 'English'), ('vi', 'Vietnamese')], max_length=10)),
                ('currency', models.CharField(choices=[('VND', 'VND'), ('HKD', 'HKD'), ('USD', 'USD')], max_length=5)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
