# Generated by Django 2.1.3 on 2018-11-14 04:28

import common.model_fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_system', '0003_auto_20181114_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', common.model_fields.LanguageField(choices=[('km', 'Cambodian'), ('en-PH', 'English'), ('id', 'Indonesian')], max_length=10, primary_key=True, serialize=False)),
                ('content', tinymce.models.HTMLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', common.model_fields.LanguageField(choices=[('km', 'Cambodian'), ('en-PH', 'English'), ('id', 'Indonesian')], max_length=10, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500)),
                ('answer', tinymce.models.HTMLField()),
                ('order', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='emailcontent',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
