# Generated by Django 2.1.3 on 2018-11-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_system', '0003_countrydefaultconfig_phone_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
