# Generated by Django 2.1.3 on 2018-11-14 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin_system', '0004_auto_20181114_0428'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='EmailContent',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
