# Generated by Django 2.1.3 on 2018-11-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_system', '0007_systemreminder_systemreminderaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('verification', 'Verification'), ('order', 'Order')], max_length=50)),
                ('method', models.CharField(choices=[('email', 'Email'), ('slack', 'Slack'), ('sms', 'SMS'), ('call', 'Call')], max_length=50)),
                ('target', models.CharField(blank=True, max_length=1000)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='systemreminderaction',
            unique_together={('group',)},
        ),
        migrations.AlterUniqueTogether(
            name='systemnotification',
            unique_together={('group', 'method')},
        ),
    ]
