# Generated by Django 2.1.3 on 2018-11-27 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin_system', '0008_auto_20181127_0345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemNotification',
        ),
        migrations.AlterUniqueTogether(
            name='systemreminderaction',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='systemreminderaction',
            name='active_reminder',
        ),
        migrations.DeleteModel(
            name='SystemReminder',
        ),
        migrations.DeleteModel(
            name='SystemReminderAction',
        ),
    ]
