# Generated by Django 2.1.3 on 2018-11-28 03:26

import common.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin_system', '0009_auto_20181127_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrydefaultconfig',
            name='language',
            field=common.model_fields.LanguageField(choices=[('km', '🇰🇭 ភាសាខ្មែរ'), ('en', '🇺🇸 English'), ('id', '🇮🇩 bahasa Indonesia'), ('hk', '🇭🇰 廣東話')], max_length=10),
        ),
    ]
