# Generated by Django 2.1.3 on 2018-12-04 07:05

import common.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin_system', '0011_auto_20181128_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularplace',
            name='language',
            field=common.model_fields.LanguageField(blank=True, choices=[('km', '🇰🇭 ភាសាខ្មែរ'), ('en', '🇺🇸 English'), ('id', '🇮🇩 bahasa Indonesia'), ('zh-Hant-HK', '🇭🇰 廣東話')], max_length=10, null=True),
        ),
    ]
