# Generated by Django 2.1.3 on 2018-12-11 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin_system', '0013_popularbank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countrycurrency',
            options={'verbose_name': 'Country Currency', 'verbose_name_plural': 'Country Currencies'},
        ),
        migrations.AlterModelOptions(
            name='countrydefaultconfig',
            options={'verbose_name': 'Country Default Config', 'verbose_name_plural': 'Country Default Configs'},
        ),
        migrations.AlterModelOptions(
            name='landingpagecontact',
            options={'verbose_name': 'Landing Page Contact', 'verbose_name_plural': 'Landing Page Contacts'},
        ),
        migrations.AlterModelOptions(
            name='popularbank',
            options={'verbose_name': 'Popular Bank', 'verbose_name_plural': 'Popular Banks'},
        ),
        migrations.AlterModelOptions(
            name='popularplace',
            options={'verbose_name': 'Popular Place', 'verbose_name_plural': 'Popular Places'},
        ),
    ]
