# Generated by Django 2.1.3 on 2018-12-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemnotification',
            name='group',
            field=models.CharField(choices=[('compare_price', 'Compare price'), ('verification', 'Verification'), ('order', 'Order')], max_length=50),
        ),
        migrations.AlterField(
            model_name='systemreminder',
            name='group',
            field=models.CharField(choices=[('compare_price', 'Compare price'), ('verification', 'Verification'), ('order', 'Order')], max_length=50),
        ),
        migrations.AlterField(
            model_name='systemreminderaction',
            name='group',
            field=models.CharField(choices=[('compare_price', 'Compare price'), ('verification', 'Verification'), ('order', 'Order')], max_length=50),
        ),
    ]
