# Generated by Django 2.1.3 on 2018-11-07 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coin_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('VN', 'Vietnam'), ('HK', 'Hong Kong')], max_length=3)),
                ('currency', models.CharField(choices=[('ETH', 'ETH'), ('BTC', 'BTC')], max_length=5)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('bank_id', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_info', models.TextField(null=True)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=30)),
                ('currency', models.CharField(choices=[('ETH', 'ETH'), ('BTC', 'BTC')], max_length=5)),
                ('fiat_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('fiat_currency', models.CharField(choices=[('VND', 'VND'), ('HKD', 'HKD'), ('USD', 'USD')], max_length=5)),
                ('fiat_local_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('fiat_local_currency', models.CharField(max_length=5)),
                ('raw_fiat_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('fiat_transferring', 'Fiat Transferring'), ('transferring', 'Transferring'), ('success', 'Success'), ('transfer_failed', 'Transfer Failed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('order_type', models.CharField(choices=[('bank', 'Bank'), ('cod', 'COD')], max_length=20)),
                ('direction', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=5)),
                ('duration', models.IntegerField(null=True)),
                ('fee_percentage', models.DecimalField(decimal_places=4, max_digits=7)),
                ('fee', models.DecimalField(decimal_places=4, max_digits=20)),
                ('address', models.CharField(max_length=100)),
                ('tx_hash', models.CharField(max_length=100, null=True)),
                ('provider_data', models.TextField(null=True)),
                ('receipt_url', models.CharField(max_length=500)),
                ('ref_code', models.CharField(max_length=10)),
                ('center', models.CharField(max_length=10)),
                ('reviewed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_orders', to='coin_user.ExchangeUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiat_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('fiat_currency', models.CharField(max_length=5)),
                ('overspent', models.DecimalField(decimal_places=4, max_digits=20)),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('under', 'Under'), ('over', 'Over')], max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_payments', to='coin_exchange.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiat_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('fiat_currency', models.CharField(max_length=5)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_details', to='coin_exchange.Payment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(choices=[('ETH', 'ETH'), ('BTC', 'BTC')], max_length=5)),
                ('direction', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=5)),
                ('limit', models.DecimalField(decimal_places=18, max_digits=30)),
                ('usage', models.DecimalField(decimal_places=18, max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name='RefCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_ref_code', to='coin_exchange.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10, null=True)),
                ('review', models.CharField(max_length=500)),
                ('visible', models.BooleanField(default=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order_review', to='coin_exchange.Order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_reviews', to='coin_user.ExchangeUser')),
            ],
        ),
        migrations.CreateModel(
            name='SellingPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=30)),
                ('currency', models.CharField(choices=[('ETH', 'ETH'), ('BTC', 'BTC')], max_length=5)),
                ('overspent', models.DecimalField(decimal_places=18, max_digits=30)),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('under', 'Under'), ('over', 'Over')], max_length=20)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selling_order_payments', to='coin_exchange.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SellingPaymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=30)),
                ('currency', models.CharField(choices=[('ETH', 'ETH'), ('BTC', 'BTC')], max_length=5)),
                ('tx_hash', models.CharField(max_length=100, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selling_payment_details', to='coin_exchange.SellingPayment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrackingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=100)),
                ('currency', models.CharField(choices=[('ETH', 'ETH'), ('BTC', 'BTC')], max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('limit', models.DecimalField(decimal_places=4, max_digits=20)),
                ('usage', models.DecimalField(decimal_places=4, max_digits=20)),
                ('fiat_currency', models.CharField(choices=[('VND', 'VND'), ('HKD', 'HKD'), ('USD', 'USD')], max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_limit', to='coin_user.ExchangeUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='pool',
            unique_together={('currency', 'direction')},
        ),
        migrations.AlterUniqueTogether(
            name='center',
            unique_together={('country', 'currency')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'order')},
        ),
    ]
