# Generated by Django 2.1.3 on 2018-11-10 18:30

import common.model_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coin_user', '0002_auto_20181108_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_info', models.TextField(null=True)),
                ('amount', common.model_fields.CryptoAmountField(decimal_places=18, max_digits=30)),
                ('currency', common.model_fields.CurrencyField(choices=[('ETH', 'ETH'), ('BTC', 'BTC')], max_length=5)),
                ('fiat_amount', common.model_fields.FiatAmountField(decimal_places=2, max_digits=18)),
                ('fiat_currency', common.model_fields.FiatCurrencyField(choices=[('VND', 'VND'), ('HKD', 'HKD'), ('USD', 'USD')], max_length=5)),
                ('fiat_local_amount', common.model_fields.FiatAmountField(decimal_places=2, max_digits=18)),
                ('fiat_local_currency', common.model_fields.FiatCurrencyField(choices=[('VND', 'VND'), ('HKD', 'HKD'), ('USD', 'USD')], max_length=5)),
                ('raw_fiat_amount', common.model_fields.FiatAmountField(decimal_places=2, max_digits=18)),
                ('price', common.model_fields.FiatAmountField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('fiat_transferring', 'Fiat Transferring'), ('transferring', 'Transferring'), ('success', 'Success'), ('transfer_failed', 'Transfer Failed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('order_type', models.CharField(choices=[('bank', 'Bank'), ('cod', 'COD')], max_length=20)),
                ('direction', common.model_fields.DirectionField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=5)),
                ('duration', models.IntegerField(null=True)),
                ('fee', common.model_fields.FiatAmountField(decimal_places=2, max_digits=18)),
                ('address', common.model_fields.CryptoHashField(max_length=255)),
                ('tx_hash', common.model_fields.CryptoHashField(max_length=255, null=True)),
                ('provider_data', models.TextField(null=True)),
                ('receipt_url', models.CharField(max_length=500)),
                ('ref_code', models.CharField(max_length=10)),
                ('center', models.CharField(max_length=10)),
                ('reviewed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_orders', to='coin_user.ExchangeUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiat_amount', common.model_fields.FiatAmountField(decimal_places=2, max_digits=18)),
                ('fiat_currency', common.model_fields.FiatCurrencyField(choices=[('VND', 'VND'), ('HKD', 'HKD'), ('USD', 'USD')], max_length=5)),
                ('overspent', common.model_fields.FiatAmountField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('under', 'Under'), ('over', 'Over')], max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_payments', to='coin_exchange.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiat_amount', common.model_fields.FiatAmountField(decimal_places=2, max_digits=18)),
                ('fiat_currency', common.model_fields.FiatCurrencyField(choices=[('VND', 'VND'), ('HKD', 'HKD'), ('USD', 'USD')], max_length=5)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_details', to='coin_exchange.Payment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', common.model_fields.CurrencyField(choices=[('ETH', 'ETH'), ('BTC', 'BTC')], max_length=5)),
                ('direction', common.model_fields.DirectionField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=5)),
                ('limit', models.DecimalField(decimal_places=18, max_digits=30)),
                ('usage', models.DecimalField(decimal_places=18, max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name='RefCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_ref_code', to='coin_exchange.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', common.model_fields.DirectionField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=5)),
                ('review', models.CharField(max_length=500)),
                ('country', common.model_fields.CountryField(choices=[('HK', 'Hong Kong'), ('VN', 'Viet Nam')], max_length=3)),
                ('visible', models.BooleanField(default=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_review', to='coin_exchange.Order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_reviews', to='coin_user.ExchangeUser')),
            ],
        ),
        migrations.CreateModel(
            name='SellingPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=100)),
                ('amount', common.model_fields.CryptoAmountField(decimal_places=18, max_digits=30)),
                ('currency', common.model_fields.CurrencyField(choices=[('ETH', 'ETH'), ('BTC', 'BTC')], max_length=5)),
                ('overspent', common.model_fields.CryptoAmountField(decimal_places=18, max_digits=30)),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('under', 'Under'), ('over', 'Over')], max_length=20)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selling_order_payments', to='coin_exchange.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SellingPaymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', common.model_fields.CryptoAmountField(decimal_places=18, max_digits=30)),
                ('currency', common.model_fields.CurrencyField(choices=[('ETH', 'ETH'), ('BTC', 'BTC')], max_length=5)),
                ('tx_hash', models.CharField(max_length=100, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selling_payment_details', to='coin_exchange.SellingPayment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrackingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', common.model_fields.CryptoHashField(max_length=255)),
                ('currency', common.model_fields.CurrencyField(choices=[('ETH', 'ETH'), ('BTC', 'BTC')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='UserLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', common.model_fields.DirectionField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=5)),
                ('limit', models.DecimalField(decimal_places=4, max_digits=20)),
                ('usage', models.DecimalField(decimal_places=4, max_digits=20)),
                ('fiat_currency', common.model_fields.FiatCurrencyField(choices=[('VND', 'VND'), ('HKD', 'HKD'), ('USD', 'USD')], max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_limit', to='coin_user.ExchangeUser')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='trackingaddress',
            unique_together={('address', 'currency')},
        ),
        migrations.AlterUniqueTogether(
            name='pool',
            unique_together={('currency', 'direction')},
        ),
        migrations.CreateModel(
            name='CODOrder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('coin_exchange.order',),
        ),
        migrations.CreateModel(
            name='SellingOrder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('coin_exchange.order',),
        ),
        migrations.AlterUniqueTogether(
            name='userlimit',
            unique_together={('user', 'direction')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'order')},
        ),
    ]
