# Generated by Django 2.1.3 on 2018-11-08 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin_exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CODOrder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('coin_exchange.order',),
        ),
        migrations.CreateModel(
            name='SellingOrder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('coin_exchange.order',),
        ),
    ]
