# Generated by Django 2.1.3 on 2018-11-19 07:23

import common.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin_exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='limit',
            field=common.model_fields.CryptoAmountField(decimal_places=18, max_digits=30),
        ),
        migrations.AlterField(
            model_name='pool',
            name='usage',
            field=common.model_fields.CryptoAmountField(decimal_places=18, max_digits=30),
        ),
        migrations.AlterField(
            model_name='userlimit',
            name='limit',
            field=common.model_fields.FiatAmountField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='userlimit',
            name='usage',
            field=common.model_fields.FiatAmountField(decimal_places=2, max_digits=18),
        ),
    ]
