# Generated by Django 2.1.3 on 2018-11-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_exchange', '0002_auto_20181119_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('fiat_transferring', 'Fiat Transferring'), ('transferring', 'Transferring'), ('transferred', 'Transferred'), ('success', 'Success'), ('transfer_failed', 'Transfer Failed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
