# Generated by Django 2.1.3 on 2018-11-09 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coin_exchange', '0002_codorder_sellingorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fiat_local_currency',
            field=models.CharField(choices=[('VND', 'VND'), ('HKD', 'HKD'), ('USD', 'USD')], max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_review', to='coin_exchange.Order'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_reviews', to='coin_user.ExchangeUser'),
        ),
    ]
