# Generated by Django 2.1.3 on 2018-11-13 11:06

import common.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin_exchange', '0003_auto_20181112_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fiat_currency',
            field=common.model_fields.FiatCurrencyField(choices=[('IDR', 'IDR'), ('PHP', 'PHP'), ('USD', 'USD')], max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='fiat_local_currency',
            field=common.model_fields.FiatCurrencyField(choices=[('IDR', 'IDR'), ('PHP', 'PHP'), ('USD', 'USD')], max_length=5),
        ),
        migrations.AlterField(
            model_name='payment',
            name='fiat_currency',
            field=common.model_fields.FiatCurrencyField(choices=[('IDR', 'IDR'), ('PHP', 'PHP'), ('USD', 'USD')], max_length=5),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='fiat_currency',
            field=common.model_fields.FiatCurrencyField(choices=[('IDR', 'IDR'), ('PHP', 'PHP'), ('USD', 'USD')], max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='country',
            field=common.model_fields.CountryField(choices=[('KH', 'Cambodia'), ('ID', 'Indonesia'), ('PH', 'Philippines')], max_length=3),
        ),
        migrations.AlterField(
            model_name='userlimit',
            name='fiat_currency',
            field=common.model_fields.FiatCurrencyField(choices=[('IDR', 'IDR'), ('PHP', 'PHP'), ('USD', 'USD')], max_length=5),
        ),
    ]
