# Generated by Django 2.1.3 on 2018-11-20 07:43

import common.model_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coin_exchange', '0003_auto_20181120_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tx_hash', common.model_fields.CryptoHashField(max_length=255)),
                ('currency', common.model_fields.CurrencyField(choices=[('ETH', 'ETH'), ('BTC', 'BTC')], max_length=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('direction', models.CharField(choices=[('in', 'Transfer In'), ('out', 'Transfer Out')], max_length=5)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_tx_hashes', to='coin_exchange.Order')),
            ],
        ),
        migrations.AddField(
            model_name='trackingaddress',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_address', to='coin_exchange.Order'),
        ),
        migrations.AlterUniqueTogether(
            name='trackingtransaction',
            unique_together={('tx_hash', 'currency')},
        ),
    ]
