# Generated by Django 2.1.3 on 2018-11-20 08:18

import common.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_exchange', '0004_auto_20181120_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fiat_currency',
            field=common.model_fields.FiatCurrencyField(choices=[('USD', 'USD'), ('HKD', 'HKD'), ('IDR', 'IDR'), ('PHP', 'PHP')], max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='fiat_local_currency',
            field=common.model_fields.FiatCurrencyField(choices=[('USD', 'USD'), ('HKD', 'HKD'), ('IDR', 'IDR'), ('PHP', 'PHP')], max_length=5),
        ),
        migrations.AlterField(
            model_name='payment',
            name='fiat_currency',
            field=common.model_fields.FiatCurrencyField(choices=[('USD', 'USD'), ('HKD', 'HKD'), ('IDR', 'IDR'), ('PHP', 'PHP')], max_length=5),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='fiat_currency',
            field=common.model_fields.FiatCurrencyField(choices=[('USD', 'USD'), ('HKD', 'HKD'), ('IDR', 'IDR'), ('PHP', 'PHP')], max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='country',
            field=common.model_fields.CountryField(choices=[('KH', 'Cambodia'), ('ID', 'Indonesia'), ('PH', 'Philippines'), ('HK', 'Hong Kong')], max_length=3),
        ),
        migrations.AlterField(
            model_name='trackingtransaction',
            name='direction',
            field=models.CharField(choices=[('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out')], max_length=5),
        ),
        migrations.AlterField(
            model_name='userlimit',
            name='fiat_currency',
            field=common.model_fields.FiatCurrencyField(choices=[('USD', 'USD'), ('HKD', 'HKD'), ('IDR', 'IDR'), ('PHP', 'PHP')], max_length=5),
        ),
    ]
