# Generated by Django 2.1.3 on 2018-11-22 03:25

import common.model_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coin_exchange', '0005_auto_20181120_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingtransaction',
            name='to_address',
            field=common.model_fields.CryptoHashField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trackingtransaction',
            name='tracking_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_transactions', to='coin_exchange.TrackingAddress'),
        ),
        migrations.AlterField(
            model_name='trackingaddress',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_address', to='coin_exchange.Order'),
        ),
        migrations.AlterField(
            model_name='trackingaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_addresses', to='coin_user.ExchangeUser'),
        ),
        migrations.AlterField(
            model_name='trackingtransaction',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_tx_hashes', to='coin_exchange.Order'),
        ),
    ]
