# Generated by Django 2.1.3 on 2018-11-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_exchange', '0006_auto_20181122_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingtransaction',
            name='direction',
            field=models.CharField(choices=[('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out')], max_length=20),
        ),
    ]
