# Generated by Django 2.1.3 on 2018-11-28 07:55

import common.model_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coin_exchange', '0007_auto_20181127_0724'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', common.model_fields.CryptoAmountField(decimal_places=18, max_digits=30)),
                ('currency', common.model_fields.CurrencyField(choices=[('ETH', 'ETH'), ('BTC', 'BTC')], max_length=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('referrer', models.BooleanField(default=True)),
                ('address', common.model_fields.CryptoHashField(max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_referrals', to='coin_exchange.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_order_referrals', to='coin_exchange.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
