# Generated by Django 2.1.3 on 2018-12-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_exchange', '0008_referralorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_user_payment_type',
            field=models.CharField(blank=True, choices=[('bank', 'Bank'), ('tng', 'TNG')], max_length=20, null=True),
        ),
    ]
