# Generated by Django 2.1.3 on 2018-12-05 07:13

import common.model_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coin_exchange', '0010_referralorder_tx_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', common.model_fields.FiatAmountField(decimal_places=2, max_digits=18)),
                ('currency', common.model_fields.FiatCurrencyField(choices=[('USD', 'USD'), ('HKD', 'HKD'), ('IDR', 'IDR'), ('PHP', 'PHP')], max_length=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('referrer', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_promotions', to='coin_exchange.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_order_promotions', to='coin_exchange.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromotionRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', common.model_fields.CountryField(choices=[('KH', 'Cambodia'), ('ID', 'Indonesia'), ('PH', 'Philippines'), ('HK', 'Hong Kong')], max_length=3)),
                ('currency', common.model_fields.FiatCurrencyField(choices=[('USD', 'USD'), ('HKD', 'HKD'), ('IDR', 'IDR'), ('PHP', 'PHP')], max_length=5)),
                ('active', models.BooleanField(default=True)),
                ('first_click_count', models.IntegerField(default=0)),
                ('first_click_amount', models.IntegerField(default=0)),
                ('first_click_days', models.IntegerField(default=0)),
                ('first_click_bonus', common.model_fields.FiatAmountField(decimal_places=2, max_digits=18)),
                ('first_referral_count', models.IntegerField(default=0)),
                ('first_referral_amount', common.model_fields.FiatAmountField(decimal_places=2, default=0, max_digits=18)),
                ('first_referral_referrer_bonus', common.model_fields.FiatAmountField(decimal_places=2, default=0, max_digits=18)),
                ('first_referral_referee_bonus', common.model_fields.FiatAmountField(decimal_places=2, default=0, max_digits=18)),
                ('referrer_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('referrer_next_duration', models.IntegerField(default=0)),
                ('referrer_percentage_2', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('referee_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('referee_next_duration', models.IntegerField(default=0)),
                ('referee_percentage_2', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromotionUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_click_count', models.IntegerField(default=0)),
                ('first_click_amount', common.model_fields.FiatAmountField(decimal_places=2, default=0, max_digits=18)),
                ('first_click_expired', models.DateTimeField(null=True)),
                ('referral_count', models.IntegerField(default=0)),
                ('currency', common.model_fields.FiatCurrencyField(choices=[('USD', 'USD'), ('HKD', 'HKD'), ('IDR', 'IDR'), ('PHP', 'PHP')], max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user_promotion', to='coin_exchange.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
