# Generated by Django 2.1.3 on 2018-12-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_exchange', '0011_promotionorder_promotionrule_promotionuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
