# Generated by Django 2.1.3 on 2018-12-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_exchange', '0013_auto_20181206_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_user_payment_type',
            field=models.CharField(blank=True, choices=[('bank', 'Bank'), ('tng', 'TNG'), ('payoneer', 'Payoneer')], max_length=20, null=True),
        ),
    ]
