# Generated by Django 2.1.3 on 2018-12-10 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coin_exchange', '0015_promotionuser_referral_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_order_promotions', to='coin_user.ExchangeUser'),
        ),
        migrations.AlterField(
            model_name='referralorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_order_referrals', to='coin_user.ExchangeUser'),
        ),
    ]
