# Generated by Django 2.1.3 on 2018-12-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_exchange', '0017_auto_20181210_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralorder',
            name='provider_data',
            field=models.TextField(null=True),
        ),
    ]
