# Generated by Django 2.1.3 on 2018-12-11 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coin_exchange', '0018_referralorder_provider_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user_promotion', to='coin_user.ExchangeUser'),
        ),
    ]
