# Generated by Django 2.1.3 on 2018-12-11 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin_exchange', '0019_auto_20181211_0323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CODOrder',
        ),
        migrations.DeleteModel(
            name='SellingCODOrder',
        ),
    ]
