# Generated by Django 2.1.3 on 2018-12-11 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin_exchange', '0020_auto_20181211_0747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Exch Order', 'verbose_name_plural': 'Exch Orders'},
        ),
        migrations.AlterModelOptions(
            name='promotionorder',
            options={'verbose_name': 'Promotion Transaction', 'verbose_name_plural': 'Promotion Transactions'},
        ),
        migrations.AlterModelOptions(
            name='promotionrule',
            options={'verbose_name': 'Promotion Rule', 'verbose_name_plural': 'Promotion Rules'},
        ),
        migrations.AlterModelOptions(
            name='referralorder',
            options={'verbose_name': 'Referral Transaction', 'verbose_name_plural': 'Referral Transactions'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='sellingorder',
            options={'verbose_name': 'Exch Selling Order', 'verbose_name_plural': 'Exch Selling Orders'},
        ),
        migrations.AlterModelOptions(
            name='trackingaddress',
            options={'verbose_name': 'Tracking Address', 'verbose_name_plural': 'Tracking Addresses'},
        ),
        migrations.AlterModelOptions(
            name='trackingtransaction',
            options={'verbose_name': 'Tracking Transaction', 'verbose_name_plural': 'Tracking Transactions'},
        ),
    ]
