# Generated by Django 2.1.3 on 2018-12-13 07:20

import common.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_exchange', '0021_auto_20181211_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', common.model_fields.CryptoAmountField(decimal_places=18, max_digits=30)),
                ('currency', common.model_fields.CurrencyField(choices=[('USDT', 'USDT'), ('ETH', 'ETH'), ('BTC', 'BTC')], max_length=5)),
                ('fund_type', models.CharField(choices=[('in_fund', 'In Fund'), ('out_fund', 'Out Fund'), ('storage_fund', 'Storage Fund')], max_length=20)),
            ],
            options={
                'verbose_name': 'Crypto Fund',
                'verbose_name_plural': 'Crypto Funds',
            },
        ),
        migrations.CreateModel(
            name='CryptoFundAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_amount', common.model_fields.CryptoAmountField(decimal_places=18, max_digits=30)),
                ('from_currency', common.model_fields.CurrencyField(choices=[('USDT', 'USDT'), ('ETH', 'ETH'), ('BTC', 'BTC')], max_length=5)),
                ('amount', common.model_fields.CryptoAmountField(decimal_places=18, max_digits=30)),
                ('currency', common.model_fields.CurrencyField(choices=[('USDT', 'USDT'), ('ETH', 'ETH'), ('BTC', 'BTC')], max_length=5)),
                ('from_fund_type', models.CharField(blank=True, choices=[('in_fund', 'In Fund'), ('out_fund', 'Out Fund'), ('storage_fund', 'Storage Fund')], max_length=20, null=True)),
                ('fund_type', models.CharField(blank=True, choices=[('in_fund', 'In Fund'), ('out_fund', 'Out Fund'), ('storage_fund', 'Storage Fund')], max_length=20, null=True)),
                ('action', models.CharField(blank=True, choices=[('update', 'Update'), ('transfer', 'Transfer'), ('convert', 'Convert')], max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('transferring', 'Transferring'), ('transferred', 'Transferred'), ('converting', 'Converting'), ('converted', 'Converted')], max_length=20, null=True)),
                ('provider_data', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Crypto Fund Action',
                'verbose_name_plural': 'Crypto Fund Actions',
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Exch Buying Order', 'verbose_name_plural': 'Exch Buying Orders'},
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=common.model_fields.CurrencyField(choices=[('USDT', 'USDT'), ('ETH', 'ETH'), ('BTC', 'BTC')], max_length=5),
        ),
        migrations.AlterField(
            model_name='pool',
            name='currency',
            field=common.model_fields.CurrencyField(choices=[('USDT', 'USDT'), ('ETH', 'ETH'), ('BTC', 'BTC')], max_length=5),
        ),
        migrations.AlterField(
            model_name='referralorder',
            name='currency',
            field=common.model_fields.CurrencyField(choices=[('USDT', 'USDT'), ('ETH', 'ETH'), ('BTC', 'BTC')], max_length=5),
        ),
        migrations.AlterField(
            model_name='sellingpayment',
            name='currency',
            field=common.model_fields.CurrencyField(choices=[('USDT', 'USDT'), ('ETH', 'ETH'), ('BTC', 'BTC')], max_length=5),
        ),
        migrations.AlterField(
            model_name='sellingpaymentdetail',
            name='currency',
            field=common.model_fields.CurrencyField(choices=[('USDT', 'USDT'), ('ETH', 'ETH'), ('BTC', 'BTC')], max_length=5),
        ),
        migrations.AlterField(
            model_name='trackingaddress',
            name='currency',
            field=common.model_fields.CurrencyField(choices=[('USDT', 'USDT'), ('ETH', 'ETH'), ('BTC', 'BTC')], max_length=5),
        ),
        migrations.AlterField(
            model_name='trackingtransaction',
            name='currency',
            field=common.model_fields.CurrencyField(choices=[('USDT', 'USDT'), ('ETH', 'ETH'), ('BTC', 'BTC')], max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='cryptofund',
            unique_together={('currency', 'fund_type')},
        ),
    ]
