# Generated by Django 2.1.4 on 2018-12-20 07:14

import common.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_exchange', '0022_auto_20181213_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoToken',
            fields=[
                ('address', common.model_fields.CryptoHashField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('protocol', models.CharField(choices=[('eip-20', 'ERC-20')], max_length=10)),
                ('decimals', models.IntegerField(default=18)),
                ('auto_price', models.BooleanField()),
                ('buy_price', common.model_fields.FiatAmountField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('sell_price', common.model_fields.FiatAmountField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Crypto Token',
                'verbose_name_plural': 'Crypto Tokens',
            },
        ),
    ]
