# Generated by Django 2.1.3 on 2018-11-15 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('id_number', models.CharField(blank=True, max_length=100)),
                ('id_type', models.CharField(choices=[('passport', 'Passport'), ('driver_license', 'Driver License'), ('id_card', 'Government ID Card')], max_length=30, null=True)),
                ('front_image', models.CharField(blank=True, max_length=500)),
                ('back_image', models.CharField(blank=True, max_length=500)),
                ('selfie_image', models.CharField(blank=True, max_length=500)),
                ('verification_level', models.CharField(choices=[('level_0', 'Not Verified'), ('level_1', 'Level 1'), ('level_2', 'Level 2'), ('level_3', 'Level 3'), ('level_4', 'Level 4')], default='level_0', max_length=30)),
                ('verification_status', models.CharField(choices=[('not_yet', 'Not Yet'), ('pending', 'Pending'), ('processing', 'Processing'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='not_yet', max_length=30)),
                ('language', models.CharField(choices=[('km', 'Cambodian'), ('en', 'English'), ('id', 'Indonesian')], max_length=10, null=True)),
                ('country', models.CharField(choices=[('KH', 'Cambodia'), ('ID', 'Indonesia'), ('PH', 'Philippines')], max_length=3, null=True)),
                ('currency', models.CharField(choices=[('IDR', 'IDR'), ('PHP', 'PHP'), ('USD', 'USD')], max_length=5, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
