# Generated by Django 2.1.3 on 2018-11-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeuser',
            name='currency',
            field=models.CharField(choices=[('VND', 'VND'), ('HKD', 'HKD'), ('USD', 'USD')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exchangeuser',
            name='verification_status',
            field=models.CharField(choices=[('not_yet', 'Not Yet'), ('pending', 'Pending'), ('processing', 'Processing'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='not_yet', max_length=30),
        ),
    ]
