# Generated by Django 2.1.3 on 2018-11-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeuser',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='exchangeuser',
            name='phone_verification_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
