# Generated by Django 2.1.3 on 2018-11-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_user', '0002_auto_20181108_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeuser',
            name='country',
            field=models.CharField(choices=[('KH', 'Cambodia'), ('ID', 'Indonesia'), ('PH', 'Philippines')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='exchangeuser',
            name='currency',
            field=models.CharField(choices=[('IDR', 'IDR'), ('PHP', 'PHP'), ('USD', 'USD')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exchangeuser',
            name='language',
            field=models.CharField(choices=[('km', 'Cambodian'), ('en-PH', 'English'), ('id', 'Indonesian')], max_length=10, null=True),
        ),
    ]
