# Generated by Django 2.1.3 on 2018-11-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_user', '0003_exchangeuser_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
