# Generated by Django 2.1.3 on 2018-11-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_user', '0005_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
