# Generated by Django 2.1.3 on 2018-11-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_user', '0007_exchangeuser_id_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeuser',
            name='country',
            field=models.CharField(choices=[('KH', 'Cambodia'), ('ID', 'Indonesia'), ('PH', 'Philippines'), ('HK', 'Hong Kong')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='exchangeuser',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('HKD', 'HKD'), ('IDR', 'IDR'), ('PHP', 'PHP')], max_length=5, null=True),
        ),
    ]
