# Generated by Django 2.1.3 on 2018-11-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_user', '0008_auto_20181120_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeuser',
            name='security_2fa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exchangeuser',
            name='security_2fa_secret',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
