# Generated by Django 2.1.3 on 2018-11-27 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coin_user', '0009_auto_20181126_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeuser',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_users', to='coin_user.ExchangeUser'),
        ),
        migrations.AlterField(
            model_name='exchangeuser',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
