# Generated by Django 2.1.3 on 2018-11-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_user', '0011_auto_20181128_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeuser',
            name='language',
            field=models.CharField(choices=[('km', '🇰🇭 ភាសាខ្មែរ'), ('en', '🇺🇸 English'), ('id', '🇮🇩 bahasa Indonesia'), ('zh-Hant-HK', '🇭🇰 廣東話')], max_length=10, null=True),
        ),
    ]
