# Generated by Django 2.1.3 on 2018-11-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_user', '0012_auto_20181128_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeuser',
            name='pending_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
