# Generated by Django 2.1.3 on 2018-12-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_user', '0016_exchangeuser_payment_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeuser',
            name='payment_verification_status',
            field=models.CharField(choices=[('not_yet', 'Not Yet'), ('pending', 'Pending'), ('processing', 'Processing'), ('rejected', 'Rejected'), ('verified', 'Verified')], default='not_yet', max_length=30),
        ),
    ]
