# Generated by Django 2.1.3 on 2018-12-04 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin_user', '0017_exchangeuser_payment_verification_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('coin_user.exchangeuser',),
        ),
    ]
