# Generated by Django 2.1.3 on 2018-12-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_user', '0018_paymentuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeuser',
            name='first_purchase',
            field=models.DateTimeField(null=True),
        ),
    ]
