# Generated by Django 2.1.3 on 2018-12-05 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin_user', '0019_auto_20181205_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeuser',
            name='first_purchase',
        ),
    ]
