# Generated by Django 2.1.3 on 2018-12-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_user', '0020_remove_exchangeuser_first_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeuser',
            name='first_purchase',
            field=models.DateTimeField(null=True),
        ),
    ]
