# Generated by Django 2.1.3 on 2018-12-11 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin_user', '0021_exchangeuser_first_purchase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangeuser',
            options={'verbose_name': 'Exch User', 'verbose_name_plural': 'Exch Users'},
        ),
        migrations.AlterModelOptions(
            name='paymentuser',
            options={'verbose_name': 'Payment Approval', 'verbose_name_plural': 'Payment Approvals'},
        ),
    ]
